Configuration et installation
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-C pull request #17
Opened 2024-10-16 15:06 UTC by scyanth

Configuration d'ESLint, Prettier, Husky, installation des packages, création de la structure

2024-10-16 15:06 UTC, JohaneDecamps submitted a review, later dismissed

2024-10-16 15:06 UTC, feub approved these changes, later dismissed

2024-10-17 07:40 UTC, jujuck requested changes
Ajoute graphQL Apollo dans le client avec la config codeGen
Ajoute les dossiers schéma et ficheirs query.ts et mutations.ts
Ajoute le dossier generated
Ajoute un dossier Page
Ajoute un dossier components

Ajoute react-router-dom et intègre le avec une première route
Vide le App.css et enlève l'import dans App.tsx

2024-10-17 09:54 UTC, JohaneDecamps approved these changes

2024-10-17 09:54 UTC, feub approved these changes
good

2024-10-17 10:23 UTC, jujuck approved these changes

2024-10-17 10:23 UTC, merged