Mise en route de la BDD
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-C pull request #22
Opened 2024-10-18 10:16 UTC by JohaneDecamps

2024-10-18 10:17 UTC, feub submitted a review, later dismissed

2024-10-18 10:17 UTC, scyanth reviewed
Yay!

2024-10-18 10:19 UTC, scyanth submitted a review, later dismissed

2024-10-18 11:53 UTC, jujuck requested changes

2024-10-18 11:53 UTC, jujuck commented on api/src/team/team.resolver.ts
> +import { Team } from "./team.entity";
A quoi sert le resolver dans la mise en place de ta BDD ?

2024-10-18 13:27 UTC, feub commented on api/src/team/team.resolver.ts
> +import { Team } from "./team.entity";
En fait, on voulait que le serveur démarre normalement en incluant la première migration de la BDD pour pouvoir valider que la la stack Apollo/GraphQL/TypeORM marche.

2024-10-23 07:24 UTC, feub approved these changes

2024-10-23 07:35 UTC, jujuck approved these changes

2024-10-23 07:35 UTC, merged