ajout page tableau de bord organisateur
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-C pull request #29
Opened 2024-10-23 14:28 UTC by scyanth

Ajout de la page de tableau de bord pour l'organisateur (gestion globale)

2024-10-23 14:34 UTC, Acetoshi approved these changes
cool, à prévoir dans le futur : peut-être utiliser une flexbox avec du gap. 
Conflit à prévoir au niveau du routeur, mais rien de particulier.

2024-10-23 14:43 UTC, feub approved these changes, later dismissed

2024-10-23 14:43 UTC, JohaneDecamps submitted a review, later dismissed

2024-10-23 14:44 UTC, Acetoshi approved these changes, later dismissed

2024-10-23 15:08 UTC, JohaneDecamps approved these changes, later dismissed

2024-10-23 15:14 UTC, jujuck requested changes

2024-10-23 15:14 UTC, jujuck commented on client/src/pages/Manage.tsx
> +            <Link href="/manage/competitions">
A reprendre... Pas de href
Pas de <a> dans un <button>

2024-10-24 09:53 UTC, JohaneDecamps approved these changes

2024-10-24 11:48 UTC, Acetoshi approved these changes
Jolie Facto, le nommage est clair :)

2024-10-24 12:15 UTC, jujuck approved these changes

2024-10-24 12:15 UTC, merged