En tant qu'organisateur je peux lister les jurys
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-C pull request #30
Opened 2024-10-23 14:40 UTC by feub

![image](https://github.com/user-attachments/assets/2411342d-9dda-4619-b92e-570206125b5c)

- API : entité/resolver pour jury
- client : page de listing des jurys (MUI)

2024-10-23 14:43 UTC, Acetoshi approved these changes, later dismissed
Beaucoup de conflits à prévoir mais très bien

2024-10-23 14:57 UTC, scyanth approved these changes, later dismissed

2024-10-23 15:06 UTC, jujuck requested changes

2024-10-23 15:06 UTC, jujuck commented on client/src/main.tsx
> +import JuriesManagement from "./pages/JuriesManagement.tsx";
Mettre de l'ordre dans les imports
- Les dépendances de node modules
- Les pages et/ou Components
- Le CSS
- Les images

2024-10-23 15:06 UTC, jujuck commented on client/src/pages/JuriesManagement.tsx
> +                {data.getAllJuries.map((jury) => (
Attention, que se passe t'il si pas de data
Mettre data &&

2024-10-23 15:08 UTC, feub commented on client/src/pages/JuriesManagement.tsx
> +                {data.getAllJuries.map((jury) => (
Il est avant en ligne 29 le data &&

2024-10-23 15:42 UTC, Acetoshi commented on client/src/pages/JuriesManagement.tsx
> +                {data.getAllJuries.map((jury) => (
@feub J'ai résolu les conflits simples mais que fait-on avec le code de codeGen ?

2024-10-24 07:44 UTC, JohaneDecamps submitted a review, later dismissed

2024-10-24 07:45 UTC, scyanth submitted a review, later dismissed

2024-10-24 08:00 UTC, jujuck requested changes

2024-10-24 08:00 UTC, jujuck commented on api/src/jury/jury.resolver.ts
> +@InputType()
Pas d'inputType

2024-10-24 08:00 UTC, jujuck commented on api/src/jury/jury.entity.ts
> +  @Column({ type: "varchar", width: 30 })
Ajout d'un unique

2024-10-24 08:58 UTC, JohaneDecamps approved these changes, later dismissed

2024-10-24 08:58 UTC, scyanth submitted a review, later dismissed

2024-10-24 08:59 UTC, Acetoshi approved these changes, later dismissed
ok

2024-10-24 12:23 UTC, scyanth approved these changes

2024-10-24 12:24 UTC, JohaneDecamps approved these changes

2024-10-24 12:25 UTC, Acetoshi approved these changes
propre

2024-10-24 12:25 UTC, jujuck approved these changes

2024-10-24 12:25 UTC, merged