Creation de la page d'accueil
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-C pull request #31
Opened 2024-10-23 14:45 UTC by JohaneDecamps

Ajout de la page d'accueil

2024-10-23 14:51 UTC, scyanth approved these changes, later dismissed

2024-10-23 15:28 UTC, Acetoshi submitted a review, later dismissed

2024-10-23 15:28 UTC, feub approved these changes, later dismissed

2024-10-24 08:22 UTC, feub approved these changes, later dismissed

2024-10-24 08:31 UTC, scyanth submitted a review, later dismissed

2024-10-24 08:33 UTC, Acetoshi requested changes
besoin d'alt sur les images

2024-10-24 08:40 UTC, feub approved these changes, later dismissed

2024-10-24 08:40 UTC, Acetoshi approved these changes, later dismissed

2024-10-24 08:56 UTC, jujuck requested changes

2024-10-24 08:56 UTC, jujuck commented on client/src/pages/HomePage.tsx
> +        </MUILink>{" "}
Il reste un espace mort

2024-10-24 08:56 UTC, jujuck commented on client/src/pages/HomePage.tsx
> +        </MUILink>{" "}
Espace mort

2024-10-24 08:56 UTC, jujuck commented on client/src/pages/HomePage.tsx
> +        Voir les classements
Pb indentation

2024-10-24 08:56 UTC, jujuck commented on client/src/pages/HomePage.tsx
> +           to="/raking"
Indentation

2024-10-24 12:56 UTC, scyanth approved these changes

2024-10-24 13:05 UTC, feub approved these changes

2024-10-24 14:19 UTC, Acetoshi approved these changes
ok

2024-10-24 14:35 UTC, jujuck approved these changes

2024-10-24 14:35 UTC, merged