Dev s1 us20 modifiy team
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-C pull request #36
Opened 2024-10-25 06:58 UTC by Acetoshi

![image](https://github.com/user-attachments/assets/715aaa8b-2893-438a-a04c-4c9e3f793b57)

2024-10-25 11:58 UTC, scyanth approved these changes, later dismissed

2024-10-25 11:58 UTC, Acetoshi commented on client/src/components/BtnTeam.tsx
Ce bouton encampsule l'édition et l'ajout de Teams

2024-10-25 11:58 UTC, Acetoshi commented on client/src/pages/TeamsManagment.tsx
Fichier renommé car comme l'a justement fait remarquer @scyanth il y avait une typo

2024-10-25 11:58 UTC, Acetoshi commented on client/src/types/graphql-types.ts
J'ai re-fait tourner code gen en m'assurant que les fonction d'ajout de Jury fonctionnaient toujours.

2024-10-25 12:00 UTC, Acetoshi commented on client/src/types/types.ts
Les types BooleanMap et RefMap devraient être suffisamment génériques pour s'adpter à d'autres tableaux dans le futur

2024-10-25 12:02 UTC, feub approved these changes, later dismissed

2024-10-25 14:21 UTC, jujuck requested changes

2024-10-25 14:21 UTC, jujuck commented on api/src/team/team.resolver.ts
> +      const teamToEdit = await Team.findOneBy({ id: newTeam.id });
En amont, il faut mettre en place la validation de la data...
const { error } = ...validate(newTeam)

En profiter pour l'ajouter sur le create

2024-10-25 14:21 UTC, jujuck commented on client/src/components/BtnTeam.tsx
> +  type: "add" | "edit";
Déclare ton type au dessus pour gagner en lisibilité

2024-10-25 14:21 UTC, jujuck commented on client/src/components/BtnTeam.tsx
> +        if (type === "add") {
Faire une variable messages = {
     add: "Erreur dans l'ajout de l'équipe, le nom est-il unique ? ",
     edit: "Erreur serveur dans l'édition l'équipe"
}
puis un seul setSnackStatus({
      message: messages[type]
})

2024-10-25 14:29 UTC, Acetoshi commented on api/src/team/team.resolver.ts
> +      const teamToEdit = await Team.findOneBy({ id: newTeam.id });
en fait pas besoin, la doc disait vrai : 
![image](https://github.com/user-attachments/assets/fe3235c0-4d1a-4ef3-99c4-56dbfa04fe50)

j'ai juste ajouté ceci : 
![image](https://github.com/user-attachments/assets/4951c691-a8ef-4999-919d-f0fdfb573ea9)

2024-10-25 14:29 UTC, Acetoshi commented on api/src/team/team.resolver.ts
> +      const teamToEdit = await Team.findOneBy({ id: newTeam.id });
Ce qui nous permet au passage de valider TOUTES les mutations ;)

2024-10-25 14:55 UTC, Acetoshi commented on client/src/components/BtnTeam.tsx
> +  type: "add" | "edit";
OK, done.

2024-10-25 14:55 UTC, Acetoshi commented on client/src/components/BtnTeam.tsx
> +        if (type === "add") {
Compacté.

2024-10-28 08:19 UTC, jujuck approved these changes

2024-10-28 08:19 UTC, merged