Dev s1 us10 ajouter un juré au jury
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-C pull request #43
Opened 2024-10-30 11:12 UTC by feub

![image](https://github.com/user-attachments/assets/5bf3d5c8-40ad-4e81-9e7a-c62bf804a7eb)

- Un utilisateur (juré) peut être ajouté à un jury
- Ajout des entités user et role
- Ajout d'un seeder pour les utilisateurs, roles, juries et user_juries_jury

Note : il y a des traces à propos du delete qui est hors de cet US, mais le composant MUI Chip a besoin du onDelete={handleDelete} pour être affiché.

2024-10-30 11:19 UTC, scyanth approved these changes, later dismissed

2024-10-30 11:27 UTC, Acetoshi reviewed
Solide. bonne base pour la suite

2024-10-30 11:28 UTC, Acetoshi submitted a review, later dismissed

2024-10-30 14:05 UTC, jujuck requested changes

2024-10-30 14:05 UTC, jujuck commented on api/src/jury/jury.resolver.ts
> +      const jury: Jury = await this.getJuryById(addUserToJury.juryId);
Faire la méthode en directe. Ne pas passer par une méthode graphQL qui se trouve exposé au client selon ton choix

2024-10-30 14:05 UTC, jujuck commented on api/src/role/role.resolver.ts
> +import { IsString, IsNotEmpty, Length } from "class-validator";
A retirer de la PR

2024-10-30 14:05 UTC, jujuck commented on api/src/user/user.resolver.ts
> +import { IsString, IsNotEmpty, Length, IsEmail } from "class-validator";
A retirer

2024-10-30 14:05 UTC, jujuck commented on client/src/schemas/queries.ts
> +export const GET_ROLE_BY_ID = gql`
A retirer

2024-10-30 14:05 UTC, jujuck commented on client/src/schemas/queries.ts
> +export const GET_JURY_BY_ID = gql`
A retirer

2024-10-30 14:05 UTC, jujuck commented on api/src/index.ts
> +    resolvers: [TeamResolver, JuryResolver, RoleResolver, UserResolver],
A retirer Role Resolver et User Resolver

2024-10-30 14:05 UTC, jujuck commented on api/src/jury/jury.resolver.ts
> +  @Query(() => [Jury])
A retirer ou ne pas exposé à graphQL (dans ce cas laisser un commentaire de code)

2024-10-30 14:05 UTC, jujuck commented on api/src/jury/jury.resolver.ts
> +      const user = new UserResolver();
Pas de resolver faire la méthode en directe avec un new User

2024-10-30 14:05 UTC, jujuck commented on api/src/jury/jury.resolver.ts
> +      const theUser: User = await user.getlUserById(addUserToJury.userId);
Attention une lettre en trop

2024-10-30 14:05 UTC, jujuck commented on client/src/components/ManageJuryAddRow.tsx
> +          refetchQueries: [{ query: GET_JURIES }],
Si tu veux, utilise la méthode refecth

2024-10-30 14:05 UTC, jujuck commented on client/src/pages/JuriesManagement.tsx
>    const { loading, error, data } = useGetAllJuriesQuery();
Si tu veux refetch, ajoute refetch

2024-10-30 14:05 UTC, jujuck commented on client/src/pages/JuriesManagement.tsx
> +              <ManageJuryAddRow />
pass refetch en props

2024-10-30 14:05 UTC, jujuck commented on client/src/components/ManageJuryRow.tsx
> +      refetchQueries: [{ query: GET_JURIES }],
A supprimer , mettre en place un state
const [juries, setJuries] = useState(jury.users)
setJuries((prev) => [...prev, result] )

2024-10-30 14:57 UTC, feub commented on api/src/user/user.resolver.ts
> +import { IsString, IsNotEmpty, Length, IsEmail } from "class-validator";
En fait, j'ai besoin d'une query user en front pour faire mon select avec getUsersByRole(). Donc il me faut un resolver pour user

2024-10-30 16:26 UTC, feub commented on client/src/components/ManageJuryRow.tsx
> +      refetchQueries: [{ query: GET_JURIES }],
Difficile de mettre en place un state, parce que je n'ajoute que l'ID du user pour l'associer au jury, je n'ai pas toutes les fins, donc je ne peux pas faire le setJuries((prev) => [...prev, result] )

2024-10-31 09:17 UTC, feub commented on api/src/index.ts
> +    resolvers: [TeamResolver, JuryResolver, RoleResolver, UserResolver],
J'ai besoin du resolver user pour le select lors de la sélection des jurés

2024-10-31 09:39 UTC, scyanth approved these changes

2024-10-31 09:46 UTC, Acetoshi approved these changes
OK pour moi.

2024-10-31 10:07 UTC, jujuck approved these changes

2024-10-31 10:07 UTC, merged