creation de la barre de navigation de l'organisateur
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-C pull request #47
Opened 2024-10-30 13:29 UTC by JohaneDecamps

![Capture d’écran 2024-10-30 à 12 34 40](https://github.com/user-attachments/assets/20db0a9a-edbd-41c1-84ec-7930ac29d1f6)

2024-10-30 13:30 UTC, scyanth approved these changes, later dismissed

2024-10-30 13:47 UTC, Acetoshi requested changes
Je pense qu'on devrait garder le NotificationProvider

2024-10-30 13:47 UTC, Acetoshi commented on client/src/App.tsx
Je pense qu'on devrait garder le NotificationProvider

2024-10-30 14:07 UTC, feub approved these changes, later dismissed

2024-10-30 14:25 UTC, scyanth approved these changes

2024-10-30 15:22 UTC, Acetoshi approved these changes

2024-10-31 07:52 UTC, jujuck approved these changes

2024-10-31 07:52 UTC, merged