Refacto s2 us10 select, amélioration UX
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-C pull request #62
Opened 2024-11-02 11:29 UTC by feub

![image](https://github.com/user-attachments/assets/6a7f47fb-deea-4d24-91be-93128b94bbf6)

- Depuis la précédente refacto liée au refetching (passage d'une requête graphql à une gestion par state), la dropdown de sélection d'ajout d'un jury ne se mettait plus jour lorsqu'on ajoutait un juré.
- Amélioration UX avec la suppression du bouton "ajouter" à droite de la dropdown. Maintenant le juré s'ajoute dès qu'on le sélectionne.

2024-11-04 10:32 UTC, Acetoshi approved these changes, later dismissed
Bonne idée !

2024-11-05 08:17 UTC, feub commented
> Bonne idée !

C'est beaucoup plus clean comme ça

2024-11-05 10:58 UTC, jujuck requested changes

2024-11-05 10:58 UTC, jujuck commented on client/src/components/ManageJuryRow.tsx
> +  if (loading)
Place tous tes return en bas
En partie haute du composant, la logique
En partie basse, le templating

2024-11-05 15:14 UTC, JohaneDecamps submitted a review, later dismissed

2024-11-05 15:15 UTC, jujuck approved these changes

2024-11-05 15:15 UTC, merged