Dev s2 us59 edit competition
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-C pull request #63
Opened 2024-11-05 15:31 UTC by scyanth

![image](https://github.com/user-attachments/assets/c92bf6b7-3e33-4157-9bb8-44cff14a5ddb)

Bouton édition + refacto ligne RowCompetition

2024-11-05 15:33 UTC, JohaneDecamps approved these changes, later dismissed

2024-11-05 16:15 UTC, feub submitted a review, later dismissed

2024-11-05 16:19 UTC, Acetoshi approved these changes, later dismissed
OK

2024-11-05 16:27 UTC, jujuck requested changes

2024-11-05 16:27 UTC, jujuck commented on client/src/components/CompetitionRow.tsx
> +              competition && displayMode == "consult"
plus de lisibilité si tu ne cascade pas les ternaire
(competition && displayMode === "consult") && new Date....
(competition && displayMode === "edit") && competition.date

2024-11-06 11:23 UTC, JohaneDecamps submitted a review, later dismissed

2024-11-06 11:32 UTC, feub submitted a review, later dismissed

2024-11-06 11:32 UTC, Acetoshi submitted a review, later dismissed

2024-11-06 13:00 UTC, jujuck approved these changes, later dismissed

2024-11-06 15:10 UTC, Acetoshi approved these changes
OKAY

2024-11-06 15:10 UTC, JohaneDecamps approved these changes

2024-11-06 15:10 UTC, feub approved these changes

2024-11-06 15:26 UTC, jujuck approved these changes

2024-11-06 15:26 UTC, merged